- id: gcs_copy_keys
  type: copy_files
  role: ['primary-controller','controller','cinder']
  requires: [pre_deployment_start]
  parameters:
    files:
      - src: /root/gcs/credentials.json
        dst: /var/lib/cinder/credentials.json
    permissions: '0600'
    dir_permissions: '0700'
  condition:
    yaql_exp: $.storage.volumes_ceph or ('cinder' in $.roles )

- id: gcs_cinder_conf
  type: puppet
  role: ['primary-controller','controller','cinder']
  requires: [deploy_start]
  version: 2.0.0
  cross-depends:
    - name: /cinder/
      role: self
  parameters:
    puppet_manifest: cinder_conf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300
  condition:
    yaql_exp: $.storage.volumes_ceph or ('cinder' in $.roles )

- id: gcs_install_packages
  type: puppet
  role: ['primary-controller','controller','cinder']
  requires: [gcs_cinder_conf]
  parameters:
    puppet_manifest: install_packages.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300
  condition:
    yaql_exp: $.storage.volumes_ceph or ('cinder' in $.roles )
