attributes:

  backup_gcs_bucket:
    value: ''
    label: 'GCS bucket name'
    description: ''
    weight: 15
    type: "text"
    regex:
      source: '^(?!\s*$).+'
      error:  'Enter the value'

  backup_gcs_project_id:
    value: ''
    label: 'GCS project ID'
    description: ''
    weight: 10
    type: "text"
    regex:
      source: '^(?!\s*$).+'
      error:  'Enter the value'

  backup_gcs_storage_class:
    value: 'NEARLINE'
    label: 'GCS storage class'
    weight: 40
    type: 'text'
    description: 'Enter or leave default class of GCS bucket'
    regex:
      source: '^(?!\s*$).+'
      error:  'Enter the value'

  backup_gcs_bucket_location:
    type: "text"
    weight: 50
    value: "US"
    label: "GCS buckel location"
    description: "Enter GCS bucket location"
    regex:
      source: '^(?!\s*$).+'
      error:  'Enter the value'

  backup_gcs_advanced_settings:
    type: "checkbox"
    weight: 60
    value: False
    label: 'Show advanced settings'
    description: 'When selected all GCS Cinder driver settings are shown'

  backup_gcs_enable_progress_timer:
    type: "checkbox"
    weight: 70
    value: True
    label: "GCS progress timer"
    description: "Timer to send the periodic progress notifications to Ceilometer when backing up the volume."
    restrictions:
      - condition: "not (settings:cinder-gcs.backup_gcs_advanced_settings.value == true )"
        action: "hide"

  backup_gcs_object_size:
    label: 'GCS Object Size'
    description: 'The size in bytes of GCS backup objects in bytes'
    type: text
    value: '52428800'
    weight: 80
    restrictions:
      - condition: "not (settings:cinder-gcs.backup_gcs_advanced_settings.value == true )"
        action: "hide"

  backup_gcs_block_size:
    label: 'GCS Block Size'
    description: 'The size in bytes that changes are tracked for incremental backups.'
    type: text
    value: '327678'
    weight: 75
    restrictions:
      - condition: "not (settings:cinder-gcs.backup_gcs_advanced_settings.value == true )"
        action: "hide"
