attributes:
  backup_gcs_project_id:
    value: ''
    label: 'GCS project ID'
    description: 'Denotes the project ID where the backup bucket will be created.'
    weight: 10
    type: 'text'
    regex:
      source: '^[A-Za-z\d_-]+$'
      error:  'The project ID where the backup bucket will be created. The value should not be empty. Only letters, digits, underscore and dash symbols are allowed.'
  backup_gcs_bucket:
    value: ''
    label: 'GCS bucket name'
    description: 'GCS bucket name to use for backup. Please refer to the official bucket naming guidelines https://cloud.google.com/storage/docs/naming .'
    weight: 15
    type: 'text'
    regex:
      source: '^[A-Za-z\d_-]+$'
      error:  'GCS bucket name to use for backup. The value should not be empty. Only letters, digits, underscore and dash symbols are allowed. The official bucket naming guidelines are at https://cloud.google.com/storage/docs/naming .'
  backup_gcs_storage_class:
    value: 'NEARLINE'
    label: 'GCS storage class'
    weight: 40
    type: 'select'
    description: 'Storage class of GCS bucket.'
    values:
      - data: 'NEARLINE'
        label: 'NEARLINE'
      - data: 'STANDARD'
        label: 'STANDARD'
      - data: 'DURABLE_REDUCED_AVAILABILITY'
        label: 'DURABLE_REDUCED_AVAILABILITY'
  backup_gcs_bucket_location:
    type: 'text'
    weight: 50
    value: 'US'
    label: 'GCS bucket location'
    description: 'Location of GCS bucket.'
    regex:
      source: '^[A-Za-z\d_-]+$'
      error:  'Location of GCS bucket. The value should not be empty. Only letters, digits, underscore and dash symbols are allowed.'
  gcs_account_type:
    label: 'GCS Account type'
    description: 'type parameter value from the GCS credentials file.'
    type: 'text'
    weight: 51
    value: 'service_account'
    regex:
      source: '^[A-Za-z\d_-]+$'
      error:  'type parameter value from the GCS credentials file. The value should not be empty. Only letters, digits, underscore and dash symbols are allowed.'
  gcs_private_key_id:
    label: 'Private Key ID'
    description: 'private_key_id parameter value from the GCS credentials file.'
    type: 'text'
    weight: 51
    value: ''
    regex:
      source: '^[A-Za-z\d]+$'
      error: 'private_key_id parameter value from the GCS credentials file. Only alphanumberic charaters are allowed.'
  gcs_private_key:
    label: 'Private Key'
    description: 'private_key parameter value from the GCS credentials file.'
    type: 'password'
    weight: 52
    value: ''
    regex:
      source: '^.+$'
      error: 'private_key parameter value from the GCS credentials file. Should not be empty.'
  gcs_client_email:
    label: 'Client E-mail'
    description: 'client_email parameter value from the GCS credentials file.'
    type: 'text'
    weight: 53
    value: ''
    regex:
      source: '^.+@(.*\..+)+$'
      error: 'client_email parameter value from the GCS credentials file. Please enter valid e-mail address.'
  gcs_client_id:
    label: 'Client ID'
    description: 'client_id parameter value from the GCS credentials file.'
    type: 'text'
    weight: 54
    value: ''
    regex:
      source: '^\d+$'
      error: 'client_id parameter value from the GCS credentials file. Only integers [1-9] are allowed.'
  gcs_auth_uri:
    label: 'Auth URI'
    description: 'auth_uri parameter value from the GCS credentials file.'
    type: 'text'
    weight: 55
    value: 'https://accounts.google.com/o/oauth2/auth'
    regex:
      source: '^https:\/\/.+$'
      error: 'auth_uri parameter value from the GCS credentials file. Please enter valid URI.'
  gcs_token_uri:
    label: 'Token URI'
    description: 'token_uri parameter value from the GCS credentials file.'
    type: 'text'
    weight: 56
    value: 'https://accounts.google.com/o/oauth2/token'
    regex:
      source: '^https:\/\/.+$'
      error: 'token_uri parameter value from the GCS credentials file. Please enter valid URI.'
  gcs_auth_provider_x509_cert_url:
    label: 'Auth Provider X509 Cert URL'
    description: 'auth_provider_x509_cert_url parameter value from the GCS credentials file.'
    type: 'text'
    weight: 57
    value: 'https://www.googleapis.com/oauth2/v1/certs'
    regex:
      source: '^https:\/\/.+$'
      error: 'auth_provider_x509_cert_url parameter value from the GCS credentials file. Please enter valid URI.'
  gcs_client_x509_cert_url:
    label: 'Client X509 Cert URL'
    description: 'client_x509_cert_url parameter value from the GCS credentials file.'
    type: 'text'
    weight: 58
    value: ''
    regex:
      source: '^https:\/\/.+$'
      error: 'client_x509_cert_url parameter value from the GCS credentials file. Please enter valid URI.'
  backup_gcs_advanced_settings:
    type: 'checkbox'
    weight: 60
    value: False
    label: 'Show advanced settings'
    description: 'When selected all GCS Cinder driver settings are shown'
  backup_gcs_object_size:
    label: 'GCS Object Size'
    description: 'The size in bytes of GCS backup objects in bytes, must be a multiple of GCS block size value, default: 52428800'
    type: 'text'
    value: '52428800'
    weight: 80
    restrictions: &hide_if_not_advanced
    regex:
      source: '^[1-9]\d*$'
      error: 'The size in bytes of GCS backup objects in bytes, must be a multiple of GCS block size value, default: 52428800 . Must be a possitive integer.'
  backup_gcs_block_size:
    label: 'GCS Block Size'
    description: 'The size in bytes that changes are tracked for incremental backups, default: 32768'
    type: 'text'
    value: '32768'
    weight: 75
    restrictions: *hide_if_not_advanced
    regex:
      source: '^[1-9]\d*$'
      error: 'The size in bytes that changes are tracked for incremental backups, default: 32768 . Must be a possitive integer.'
  backup_gcs_user_agent:
    label: 'HTTP User-Agent'
    description: 'HTTP User-Agent string for the GCS API, default: gcscinder'
    type: 'text'
    value: 'gcscinder'
    weight: 85
    restrictions: *hide_if_not_advanced
  backup_gcs_writer_chunk_size:
    label: 'GCS writer Chunk Size'
    description: 'Chunk size for GCS object uploads in bytes, -1 for single chunk, default value: 2097152, maximum value: 52428800'
    type: 'text'
    value: '2097152'
    weight: 90
    regex:
      source: '^((-1$)|(([1-9])\d{0,7}$))'
      error: 'Chunk size for GCS object uploads in bytes, -1 for single chunk, default value: 2097152, maximum value: 52428800 . Must be a possitive integer or -1 .'
    restrictions: *hide_if_not_advanced
  backup_gcs_reader_chunk_size:
    label: 'GCS Reader Chunk Size'
    description: 'Chunk size for GCS object downloads in bytes, default: 2097152'
    type: 'text'
    value: '2097152'
    weight: 95
    restrictions: *hide_if_not_advanced
    regex:
      source: '^((-1$)|(([1-9])\d*$))'
      error: 'Chunk size for GCS object downloads in bytes, default: 2097152 . Must be a possitive integer.'
  backup_gcs_retry_error_codes:
    label: 'GCS Retry Error Codes'
    description: 'List of GCS error codes for which to initiate a retry, default: 429'
    type: 'text'
    value: '429'
    weight: 100
    restrictions: *hide_if_not_advanced
    regex:
      source: '^([4-5][0-9]{2})(,\s{1}[4-5][0-9]{2})*$'
      error:  'Enter list of valid error codes, example: 403, 404, 503'
  backup_gcs_num_retries:
    label: 'GCS Retries Number'
    description: 'Number of times to retry transfers'
    type: 'text'
    value: '3'
    weight: 105
    restrictions: *hide_if_not_advanced
    regex:
      source: '^[1-9]\d{0,2}$'
      error: 'Number of times to retry transfers. Must be an integer in range of 1-999 .'
  backup_gcs_enable_progress_timer:
    type: 'checkbox'
    weight: 110
    value: True
    label: 'GCS progress update timer'
    description: 'Timer to send the periodic progress notifications to Ceilometer when backing up the volume.'
    restrictions: *hide_if_not_advanced
